### ISSUE TITLE
ModuleNotFoundError: No module named 'igibson.agents'

### ISSUE THREAD

**Issue by zhibinQiu** [StanfordVL/Sonicverse#1]
Nice work!  when I try to run , I get this error:
<img width="789" alt="image" src="https://github.com/StanfordVL/Sonicverse/assets/33189663/9de0e73e-dddf-45e2-abd2-b08204c6f005">
I also can't find the location of the package igibson.agents in the code, is this a bug? Or is there something wrong with my environment configuration.

**Comment by hao-l1** [comment]
Hi @zhibinQiu , sorry for the late reply. I don't know why I didn't receive any notification for the issues. The agents module is for the RL models. An example agent is like this one https://github.com/facebookresearch/sound-spaces/tree/main/ss_baselines/av_nav . I delete the agent modules since the code is kind of messy at the moment. But you can create you own agent following the code is the above repo.

Here are the three maps imported, you can paste it somewhere in this file:

```
# for igibson
CATEGORIES = ['straight_chair', 'breakfast_table', 'picture', 'bottom_cabinet', 'cushion', 'sofa', 'bed', 'shelf', 'sink', 'toilet', 'stool', 'standing_tv', 'shower', 'bathtub', 'countertop']

CATEGORY_MAP = {
                'straight_chair': 0,
                'breakfast_table': 1,
                'picture': 2,
                'bottom_cabinet': 3,
                'cushion': 4,
                'sofa': 5,
                'bed': 6,
                'shelf': 7,
                'sink': 8,
                'toilet': 9,
                'stool': 10,
                'standing_tv': 11,
                'shower': 12,
                'bathtub': 13,
                'countertop': 14,
            }

MAP_SIZE = {
                "Beechwood_0_int": 2400,
                "Beechwood_1_int": 2400,
                "Benevolence_0_int": 1800,
                "Benevolence_1_int": 2000,
                "Benevolence_2_int": 1800,
                "Ihlen_0_int": 2400,
                "Ihlen_1_int": 2200,
                "Merom_0_int": 2200,
                "Merom_1_int": 2200,
                "Pomaria_0_int": 2800,
                "Pomaria_1_int": 2800,
                "Pomaria_2_int": 1600,
                "Rs_int": 1000,   
                "Wainscott_0_int": 3000,
                "Wainscott_1_int": 2800,
            }
```

**Comment by zhibinQiu** [comment]
@HaoLiRobo Thank you very much for your reply, will this repository be updated to a full version in the future? If I want to use a simulation environment with audio, is it better to use "OmniGibson" or this "SONICVERSE"?

**Comment by hao-l1** [comment]
@zhibinQiu Thanks for the questions. The current version of OmniGibson does not support audio simulation. There is a plan undergoing to add audio support but the exact date of when it will be released is unknown. 

The current version of SONICVERSE is workable and supports audio simulation. The only thing it is missing is the RL model used in the paper. I'll cleanup the codebase the upload it sometime in the future when I'm free (I'm kind of busy due to my incoming qual exams). If you don't mind implementing your own RL model, you can use this current version. The audio system example can give you a simple audio simulation with robot moving forward while audio playing.
